# frozen_string_literal: true

require "rake"
require_relative "../bin/shared/constants"

namespace :masOS do
  desc "installs macOS devtools"
  task :devtools do
    system("xcode-select --install")
  end

  desc "installs brew packages"
  task :brew do
    system("/usr/bin/ruby -e \"$(curl -fsSL #{Const::URL::GitHub::HOMEBREW})\"")
    system("brew tap Homebrew/bundle")
    system("brew bundle")
  end

  desc "installs global gems"
  task :gems do
    system("gem install bundler")
    system("bundle install --system --gemfile #{Const::Dotfiles::Setup::GLOBAL_GEMFILE_PATH}")
  end

  task all: %w[devtools brew gems]
end

namespace :install do
  desc "install zsh"
  task :zsh do
    system("sh -c \"$(curl -fsSL #{Const::URL::GitHub::OH_MY_ZSH})\"")
  end

  desc "clone spacemacs"
  task :spacemacs do
    system("git clone #{Const::URL::GitHub::SPACEMACS} ~/.emacs.d")
  end

  task all: %w[zsh spacemacs]
end

namespace :dotfiles do
  desc "clones my dotfiles repository"
  task :clone do
    system("git clone #{Const::URL::GitHub::DOTFILES} ~/")
  end

  desc "copies dotfiles to their appropriate locations"
  task :copy do
    system("cp #{Const::Dotfiles::Emacs::SPACEMACS_PATH} ~/")
    system("rsync -r #{Const::Dotfiles::Emacs::PRIVATE_PATH} ~/.emacs.d/")
    system("cp #{Const::Dotfiles::Zsh::RC_PATH} ~/")
    system("cp #{Const::Dotfiles::Zsh::ENV_PATH} ~/")
    system("cp #{Const::Dotfiles::Ruby::RUBOCOP_PATH} ~/")
  end

  task all: %w[clone copy]
end
