# frozen_string_literal: true

require "rake"
require_relative "../bin/shared/constants"

namespace :masOS do
  desc "installs macOS devtools"
  task :devtools do
    system("xcode-select --install")
  end

  desc "installs brew packages"
  task :brew do
    system("/usr/bin/ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\"")
    system("brew tap Homebrew/bundle")
    system("brew bundle")
  end

  task all: %w[devtools brew]
end

namespace :install do
  desc "install zsh"
  task :zsh do
    system("sh -c \"$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)\"")
  end

  desc "clone spacemacs"
  task :spacemacs do
    system("git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d")
  end

  task all: %w[zsh spacemacs]
end

namespace :dotfiles do
  desc "copies dotfiles to their appropriate locations"
  task :copy do
    system("cp #{Const::Dotfiles::Emacs::SPACEMACS_PATH} ~/.spacemacs")
    system("rsync -r #{Const::Dotfiles::Emacs::PRIVATE_PATH} ~/.emacs.d/private/")
    system("cp #{Const::Dotfiles::Zsh::RC_PATH} ~/.zshrc")
    system("cp #{Const::Dotfiles::Zsh::ENV_PATH} ~/.zshenv")
    system("cp #{Const::Dotfiles::Ruby::RUBOCOP_PATH} ~/.rubocop.yml")
  end

  task all: %w[copy]
end
