# frozen_string_literal: true

require "rake"

namespace :masOS do
  desc "installs macOS devtools"
  task :devtools do
    system("xcode-select --install")
  end

  desc "installs brew packages"
  task :brew do
    system("/usr/bin/ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\"")
    system("brew tap Homebrew/bundle")
    system("brew bundle")
  end

  task all: %w[devtools brew]
end

namespace :install do
  desc "install zsh"
  task :zsh do
    system("sh -c \"$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)\"")
  end

  desc "install powerline"
  task :powerline do
    system("git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k")
  end

  desc "clone spacemacs"
  task :spacemacs do
    system("git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d")
  end

  task all: %w[zsh powerline spacemacs]
end

namespace :dotfiles do
  desc "copies dotfiles to their appropriate locations"
  task :copy do
    system("cp ~/.dotfiles/editor/+emacs/.spacemacs ~/.spacemacs")
    system("rsync -r ~/.dotfiles/editor/+emacs/private/ ~/.emacs.d/private/")
    system("cp ~/.dotfiles/tools/+zsh/.zshrc ~/.zshrc")
    system("cp ~/.dotfiles/tools/+zsh/.zshenv ~/.zshenv")
    system("cp ~/.dotfiles/lang/+ruby/.rubocop.yml ~/.rubocop.yml")
  end

  task all: %w[copy]
end
