* =/.dotfiles=
This repository contains my personal dotfiles used in my everyday development.

** Structure
#+BEGIN_SRC bash
$ tree /Users/armcburney/.dotfiles

/Users/armcburney/.dotfiles
├── +cvim
│   ├── cvim_styles.css
│   └── cvimrc.vim
├── +emacs
│   ├── private
│   ├── .spacemacs
│   └── custom.el
├── +hammerspoon
│   ├── hs-hybrid
│   ├── hs-keys
│   ├── hs-music
│   └── init.lua
├── +hg
│   └── .hgrc
├── +iterm2
│   └── AndrewsTermTheme.itermcolors
├── +ruby
│   └── .rubocop.yml
├── +zsh
│   ├── .zshenv
│   ├── .zshrc
│   ├── alias
│   ├── functions
│   ├── loaders
│   └── theme
├── .setup
│   ├── Brewfile
│   └── Rakefile
├── bin
│   ├── commands
│   ├── models
│   ├── scripts
│   ├── shared
│   ├── dev
│   ├── dev-copy
│   ├── dev-port
│   ├── dev-ports
│   ├── gh
│   ├── goals
│   ├── org-goals-report
│   └── xcode-add
└── Rakefile

17 directories, 25 files

#+END_SRC
*** =/.dotfiles/+cvim=
My cvim configuration file and custom styles.

*** =/.dotfiles/+emacs=
My spacemacs configuration file, YASnippet definitions, and custom elisp configuration code.

*** =/.dotfiles/+hammerspoon=
My hammerspoon macOS desktop automation configuration.

*** =/.dotfiles/+hg=
My mercurial version control setup, compatible with multi-term in emacs.

*** =/.dotfiles/+iterm2=
My iterm2 color configuration.

*** =/.dotfiles/+ruby=
Contains my global =.rubocop.yml= configuration file.

*** =/.dotfiles/+zsh=
Configuration for [[https://github.com/robbyrussell/oh-my-zsh][oh-my-zsh]] and a few shell functions.

*** =/.dotfiles/.setup=
A =Brewfile= containing packages I use on my macOS machines, and a Rakefile to install and setup my macOS and Linux machines.

*** =/.dotfiles/bin=
A collection of scripts to be added to my =$PATH=.

*** =/.dotfiles/Rakefile=
** Setup
*1. Clone the repository.*
#+BEGIN_SRC bash
git clone https://github.com/AndrewMcBurney/.dotfiles.git
#+END_SRC

*2. Run the setup script.*
#+BEGIN_SRC bash
cd ~/.dotfiles/.setup && rake
#+END_SRC
