#!/bin/sh

# ******************************************************************************
# ZSH Loaders
# Maintained by: Andrew McBurney
# ******************************************************************************

# Reverse image search with fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
