#
# My ~/.zshrc file
#

# Exports
export PATH=$HOME/bin:/usr/local/bin:$PATH
export ZSH=/Users/andrewmcburney/.oh-my-zsh
export PATH="$PATH:$HOME/.skeleton/bin/run"
export UPDATE_ZSH_DAYS=7

# I have a different theme for emacs terminal emulator
if [ -n "$INSIDE_EMACS" ]; then
  ZSH_THEME="pure"
else
  ZSH_THEME="powerlevel9k/powerlevel9k"
  POWERLEVEL9K_MODE='awesome-patched'
  POWERLEVEL9K_PROMPT_ON_NEWLINE=true
  POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%{%F{249}%}\u250f"
  POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="%{%F{249}%}\u2517%{%F{default}%} "
  POWERLEVEL9K_SHORTEN_DIR_LENGTH=4
  POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
  POWERLEVEL9K_OS_ICON_BACKGROUND="black"
  POWERLEVEL9K_OS_ICON_FOREGROUND="249"
  POWERLEVEL9K_TODO_BACKGROUND="black"
  POWERLEVEL9K_TODO_FOREGROUND="249"
  POWERLEVEL9K_DIR_HOME_BACKGROUND="black"
  POWERLEVEL9K_DIR_HOME_FOREGROUND="249"
  POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="black"
  POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="249"
  POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="black"
  POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="249"
  POWERLEVEL9K_STATUS_OK_BACKGROUND="black"
  POWERLEVEL9K_STATUS_OK_FOREGROUND="green"
  POWERLEVEL9K_STATUS_ERROR_BACKGROUND="black"
  POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"
  POWERLEVEL9K_NODE_VERSION_BACKGROUND="black"
  POWERLEVEL9K_NODE_VERSION_FOREGROUND="249"
  POWERLEVEL9K_NODE_VERSION_VISUAL_IDENTIFIER_COLOR="green"
  POWERLEVEL9K_RVM_BACKGROUND="black"
  POWERLEVEL9K_RVM_FOREGROUND="249"
  POWERLEVEL9K_RVM_VISUAL_IDENTIFIER_COLOR="red"
  POWERLEVEL9K_IP_BACKGROUND="black"
  POWERLEVEL9K_IP_FOREGROUND="249"
  POWERLEVEL9K_IP_VISUAL_IDENTIFIER_COLOR="green"
  POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND="black"
  POWERLEVEL9K_LOAD_WARNING_BACKGROUND="black"
  POWERLEVEL9K_LOAD_NORMAL_BACKGROUND="black"
  POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND="249"
  POWERLEVEL9K_LOAD_WARNING_FOREGROUND="249"
  POWERLEVEL9K_LOAD_NORMAL_FOREGROUND="249"
  POWERLEVEL9K_LOAD_CRITICAL_VISUAL_IDENTIFIER_COLOR="red"
  POWERLEVEL9K_LOAD_WARNING_VISUAL_IDENTIFIER_COLOR="yellow"
  POWERLEVEL9K_LOAD_NORMAL_VISUAL_IDENTIFIER_COLOR="green"
  POWERLEVEL9K_RAM_BACKGROUND="black"
  POWERLEVEL9K_RAM_FOREGROUND="249"
  POWERLEVEL9K_RAM_ELEMENTS=(ram_free)
  POWERLEVEL9K_BATTERY_LOW_BACKGROUND="black"
  POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND="black"
  POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND="black"
  POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND="black"
  POWERLEVEL9K_BATTERY_LOW_FOREGROUND="249"
  POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND="249"
  POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND="249"
  POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND="249"
  POWERLEVEL9K_BATTERY_LOW_VISUAL_IDENTIFIER_COLOR="red"
  POWERLEVEL9K_BATTERY_CHARGING_VISUAL_IDENTIFIER_COLOR="yellow"
  POWERLEVEL9K_BATTERY_CHARGED_VISUAL_IDENTIFIER_COLOR="green"
  POWERLEVEL9K_BATTERY_DISCONNECTED_VISUAL_IDENTIFIER_COLOR="249"
  POWERLEVEL9K_TIME_BACKGROUND="black"
  POWERLEVEL9K_TIME_FOREGROUND="249"
  POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S} \UE12E"
  POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=('context' 'dir' 'vcs' 'os_icon')
  POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=('status' 'node_version' 'rvm' 'ip' 'battery' 'time')
fi

COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(git vi-mode)

source $ZSH/oh-my-zsh.sh

# ls every time you cd
function cd { builtin cd "$@" && ls }

# Aliases
alias a="clear"
alias sk="skeleton"
alias sshuw='ssh -Y armcburn@linux.student.cs.uwaterloo.ca'
alias ssham='ssh root@138.197.135.132'
