# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.ssh.forward_agent = true

  config.vm.provision :chef_solo do |chef|
    chef.data_bags_path = "databags"
    chef.cookbooks_path = ["cookbooks", "site-cookbooks"]
    chef.add_recipe "vim"
    chef.add_recipe "git"
    chef.add_recipe "users::ruby_shadow"
    chef.add_recipe "users::sysadmins"
    chef.add_recipe "users::sysadmin_sudo"
    chef.add_recipe "root_ssh_agent::ppid"
    chef.add_recipe "ssh_known_hosts"
    chef.add_recipe "homesick_agent::data_bag"
    chef.json = {
      users: ["testuser"]
    }
    chef.log_level = :debug
  end
end
