#!/bin/sh

# ******************************************************************************
# ZSH Aliases
# Maintained by: Andrew McBurney
# ******************************************************************************

# emacs
alias ed="emacs --daemon"
alias ek="emacsclient -e \"(kill-emacs)\""
alias em="emacsclient -t"

# ssh
alias uwilin='ssh -Y armcburn@linux.student.cs.uwaterloo.ca'

# overwrites
alias cp="cp -r"
alias mkdir="mkdir -p"

# docker
alias dka='docker kill $(docker ps -q)'

# git
alias gdh='git diff HEAD'

# general
alias c="clear"
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls -G'
alias k9='kill -9'
alias port='lsof -i -P -n | grep'
alias net='netstat -vanp tcp | grep'
alias fs='foreman start'

# kubernetes
alias k='kubectl'
alias kt='kubetail'
alias kci='k cluster-info'

# kube-fzf
alias fp='findpod'
alias dp='describepod'
alias tp='tailpod'
ep() {
    execpod "$1" bash
}
