#!/bin/sh

# ******************************************************************************
# ZSH Loaders
# Maintained by: Andrew McBurney
# ******************************************************************************

# Reverse image search with fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Pyenv and virtualenv.
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
