#!/bin/sh

# ******************************************************************************
# ZSH Loaders
# Maintained by: Andrew McBurney
# ******************************************************************************

# Pyenv and virtualenv.
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
