#!/bin/sh

# ******************************************************************************
# ZSH Aliases
# Maintained by: Andrew McBurney
# ******************************************************************************

# emacs
alias ed="emacs --daemon"
alias ek="emacsclient -e \"(kill-emacs)\""
alias em="emacsclient -t"

# ssh
alias sshuw='ssh -Y armcburn@linux.student.cs.uwaterloo.ca'
alias sshece='ssh -X armcburn@ecelinux4.uwaterloo.ca'

# overwrites
alias cp="cp -r"
alias mkdir="mkdir -p"

# datadog
alias da='/usr/local/bin/datadog-agent'
alias dai='/usr/local/bin/datadog-agent info -v'
alias ta='~/trace-agent-osx -ddconfig ~/.datadog-agent/datadog.conf'

# docker
alias dka='docker kill $(docker ps -q)'

# git
alias gdh='git diff HEAD'

# general
alias c="clear"
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls -G'
alias k9='kill -9'
alias port='lsof -i -P -n | grep'
alias net='netstat -vanp tcp | grep'
alias fs='foreman start'

# go
alias gdbnew='/usr/local/Cellar/gdb/7.6/bin/gdb'
