#!/bin/sh

# ******************************************************************************
# Functions
# Maintained by: Andrew McBurney
# ******************************************************************************

# ls whenever you cd.
function cd {
  builtin cd "$@" && ls
}

# fuzzy grep open via ag
function vg {
    local file

    file="$(ag --nobreak --noheading $@ | fzf -0 -1 | awk -F: '{print $1 " +" $2}')"

    if [[ -n $file ]]
    then
        vim $file
    fi
}

# fd - cd to selected directory
function fd {
    local dir
    dir=$(find ${1:-.} -path '*/\.*' -prune \
               -o -type d -print 2> /dev/null | fzf +m) &&
        cd "$dir"
}

# fh - repeat history
function fh {
    eval $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed 's/ *[0-9]* *//')
}

# fkill - kill process
function fkill {
    local pid
    pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')

    if [ "x$pid" != "x" ]
    then
        echo $pid | xargs kill -${1:-9}
    fi
}
