#!/bin/sh

# ******************************************************************************
# Functions
# Maintained by: Andrew McBurney
# ******************************************************************************

# ls whenever you cd.
function cd {
  builtin cd "$@" && ls
}
